name: github action 실행시켜보기

on:
  push:
    branches:
      - main

jobs:
  My-deploy-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world 출력하기
        run: echo "Hello, world!"

      - name: 여러 명령어 문장 작성하기
        run: |
          echo "good"
          echo "morning"
          pwd

      - name: Git Actions 자체 저장되어 있는 변수 사용해보기
        run: |
          echo $GITHUB_REPOSITORY
          echo $GITHUB_SHA
